### ISSUE TITLE
Request: Taxi FTP client

### ISSUE THREAD

**Issue by quassy** [SomeElementary/PPA-Issues#1]
Please package [Taxi](http://quassy.github.io/elementary-apps/Taxi/), [build instructions](http://bazaar.launchpad.net/~khampal/taxi/trunk/view/head:/INSTALL) are available on Launchpad.

**Comment by JustSomeDood** [comment]
Taxi has already been packaged but when I uploaded it to launchpad the build failed.  I'll take a look at it again.

**Comment by JustSomeDood** [comment]
@quassy taxi is now packaged, closing issue.
