### ISSUE TITLE
[Elementary] Add some apps 

### ISSUE THREAD

**Issue by bil-elmoussaoui** [SomeElementary/PPA-Issues#4]
Hello, 
I would like to ask you to add Vocal,photostream(instagram client) and footnote to your official PPA

the apps are here : http://quassy.github.io/elementary-apps/apps/
thank you !!

**Comment by JustSomeDood** [comment]
photostream should be coming soon, I am hesitant on footnote since it's in the official repo but if it's requested then i'll do it.  As far as vocal i'll look into that one too

**Comment by bil-elmoussaoui** [comment]
I will wait at moment until i got any answer from the dev. as it has been more than 3 months since the last commit in his personal repo. Thank you!!
